lazy added
xosmig/kotlin_homeworks pull request #1
Opened 2017-02-16 22:12 UTC by xosmig

2017-02-20 21:16 UTC, yurii-litvinov requested changes
В целом всё правильно, но кое-что можно исправить --- например, double-checked locking

2017-02-20 21:16 UTC, yurii-litvinov commented on lazy/src/main/kotlin/com/xosmig/lazy/Lazy.kt
> +    private var result: Any? = NOTHING
Тут где-то должно быть @Volatile. Иначе могут быть проблемы, описанные в https://en.wikipedia.org/wiki/Double-checked_locking (если Котлин специально сам с ними не борется, я в Котлине не шарю).

2017-02-20 21:16 UTC, yurii-litvinov commented on lazy/src/main/kotlin/com/xosmig/lazy/Lazy.kt
> +    private var result: AtomicReference<Any?> = AtomicReference(NOTHING)
AtomicReferenceFieldUpdater не лучше ли в плане использования памяти, если LockFreeLazyExpr-ов может быть много?

2017-02-20 21:16 UTC, yurii-litvinov commented on lazy/src/test/kotlin/com/xosmig/lazy/LazyTest.kt
> +        val lazyHello2: Lazy<Any> = lazyHello1  // O_o
мм, ковариантность в действии

2017-02-20 21:16 UTC, yurii-litvinov commented on lazy/src/test/kotlin/com/xosmig/lazy/LazyTest.kt
> +            antiOptimizer = (antiOptimizer + i) % 123456789
Здесь выдаёт предупреждение "Warning:(44, 49) Kotlin: 'mod(Int): Long' is deprecated. Use rem(other) instead"

2017-02-25 10:09 UTC, xosmig commented on lazy/src/test/kotlin/com/xosmig/lazy/LazyTest.kt
> +            antiOptimizer = (antiOptimizer + i) % 123456789
Кажется, у вас слишком новая (не stable) версия

2017-02-25 18:33 UTC, yurii-litvinov approved these changes
Теперь всё ок, зачтена

2017-02-25 18:33 UTC, yurii-litvinov commented on lazy/src/test/kotlin/com/xosmig/lazy/LazyTest.kt
> +            antiOptimizer = (antiOptimizer + i) % 123456789
Вполне возможно, да

2017-03-06 18:09 UTC, merged